# builds backend docker image and bootstraps it with all the dependencies

version: '3.3'
services:
  backend:
    build: .
    image: localhost/backend-master:latest
    ports:
    - "8080:8080"
    environment:
      APP_ENV: local
