# Bootstraps entire app, frontend, backend and supporting artifacts (persistence, etc)
# from images built for a production release
#
version: '3.3'
services:
  frontend:
    image: docker.pkg.github.com/mrazjava/booklink/web-master:latest
    ports:
      - "8090:80"
    environment:
      VUE_APP_BACKEND_URL: http://localhost:8080
      VUE_APP_ENV: local
  backend:
    image: docker.pkg.github.com/mrazjava/booklink/backend-master:latest
    ports:
    - "8080:8080"
    environment:
      APP_ENV: local
