# builds backend docker image and bootstraps it with all the dependencies
#
version: '3.1'

services:

  pg:
    image: postgres:12.2 # https://hub.docker.com/_/postgres
    restart: always
    environment:
      POSTGRES_DB: booklink
      POSTGRES_USER: bookworm
      POSTGRES_PASSWORD: BL
    ports:
      - 127.0.0.1:5433:5432