# Bootstraps entire app, frontend, backend and supporting artifacts (persistence, etc) from 
# custom built local images
version: '3.3'
services:
  frontend:
    image: local/booklink-web:latest
    ports:
      - "8090:80"
    environment:
      VUE_APP_BACKEND_HOST: http://localhost:8080
      VUE_APP_ENV: local
  backend:
    image: local/booklink-backend:latest
    ports:
    - "8080:8080"
    environment:
      APP_ENV: local
