# Used for local dev only. If enabled, sandbox resources are not necessary because
# this profile attempts to use remote AWS pre-release resources instead (eg: db).
# Requires AWS credentials.
#
# Helpful: environmental variable configuration:
# https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
# https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html
#
# RUN COMMAND:
# mvn clean spring-boot:run -Dspring-boot.run.profiles=pre-aws
# -Dspring-boot.run.jvmArguments="-Daws.accessKeyId= -Daws.secretKey= -Daws.region=eu-central-1"
#
# You can setup and run against your own AWS infrastructure or, you must inquire with me (mrazjava)
# for access to official AWS environment for booklinktrove.
#
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc-secretsmanager:postgresql://pre-1.cnzxipfrf9ok.eu-central-1.rds.amazonaws.com:5432/booklink
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    username: pre1/postgres
    initialization-mode: never