spring:
  jackson:
    default-property-inclusion: NON_NULL
  profiles:
    active: ${APP_ENV:local}
  cache:
    jcache:
      config: classpath:ehcache.xml
  mustache:
    check-template-location: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${APP_BE_HIBERNATE_DDL_AUTO:create}
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false
  datasource:
    platform: postgresql
    driver-class-name: ${APP_SPRING_DATA_DRIVER:org.postgresql.Driver}
    initialization-mode: ${APP_SPRING_DATA_INIT:always}
    url: ${APP_BE_DB_URL:jdbc:postgresql://localhost:5432/booklink?currentSchema=local}
    username: ${APP_BE_DB_USERNAME:bookworm}
    password: ${APP_BE_DB_PASSWORD:BL}
    max-active: 5
    initial-size: 2
    max-idle: 2
    min-idle: 1
    test-while-idle: true
    test-on-borrow: true
    validation-query: select 1
    validation-interval: 45000 # 45(s)
    hikari:
      connection-timeout: ${APP_HIKARI_CON_TIMEOUT:1500}
  flyway:
    enabled: ${APP_FLYWAY_ENABLED:false}
info:
  app:
    home-page: ${APP_BASE_URL:http://localhost:8080}/swagger-ui.html
    health: ${APP_BASE_URL:http://localhost:8080}/actuator/health
    git-repo: https://github.com/mrazjava/booklink
    description: "@project.description@"
server:
  error:
    include-stacktrace: never
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      cors:
        allowed-origins: ${CORS_ALLOW_ORIGINS:http://localhost:8090}
        allowed-methods: GET
booklink:
  auth-token-pattern: ${AUTH_TOKEN_PATTERN:}
  depot:
    url: ${DEPOT_URL:http://localhost:8070/}
  security:
    cors-allow-origins: ${CORS_ALLOW_ORIGINS:http://localhost:8090}
swaggerhost: ${APP_SWAGGERHOST:localhost:8080}