#
# Enables schema build script. If enabled, hibernate validation is not executed
# even if ${spring.jpa.hibernate.ddl-auto:validate} is set. Enable this only
# temporarily, during developement to compute schema difference for schema
# migration purposes. This should never be checked in commented out.
#
#spring:
#  jpa:
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: target/schema-dev.sql

booklink:
  security:
    cors-allow-origins:
      - http://localhost:8090
logging:
  pattern:
    console: '%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr([%30.30M]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n'