cloud:
  aws:
    stack:
      auto: true
    credentials:
      useDefaultAwsCredentialsChain: true
      accessKey: ${AWS_ACCESS_KEY_ID:}
      secretKey: ${AWS_SECRET_ACCESS_KEY:}
    region:
      static: ${AWS_REGION:eu-central-1}