spring:
  profiles:
    active: ${APP_ENV:local}
  cache:
    jcache:
      config: classpath:ehcache.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${APP_BE_HIBERNATE_DDL_AUTO:create}
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false
  datasource:
    platform: postgresql
    driver-class-name: ${APP_SPRING_DATA_DRIVER:org.postgresql.Driver}
    initialization-mode: ${APP_SPRING_DATA_INIT:always}
    url: ${APP_BE_DB_URL:jdbc:postgresql://localhost:5433/booklink}
    username: ${APP_BE_DB_USERNAME:bookworm}
    password: ${APP_BE_DB_PASSWORD:BL}
    hikari:
      connection-timeout: ${APP_HIKARI_CON_TIMEOUT:5000}
      connection-test-query: select 1
  flyway:
    enabled: ${APP_FLYWAY_ENABLED:false}
info:
  app:
    home-page: ${APP_BASE_URL:http://localhost:8080}/swagger-ui.html
    git-repo: https://github.com/mrazjava/booklink
    description: "@project.description@"
management:
  info:
    git:
      mode: full
  health:
      enabled: true
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,loggers
booklink:
  security:
    cors-allow-origins: ${CORS_ALLOW_ORIGINS:}
