CREATE SEQUENCE user_sequence increment by 1 start 6;
CREATE TABLE bl_user_origin (id int8 NOT NULL, origin_name varchar(255) NULL, CONSTRAINT pk_user_origin PRIMARY KEY (id));
INSERT INTO bl_user_origin(id, origin_name) VALUES(1, 'BOOKLINK');
INSERT INTO bl_user_origin(id, origin_name) VALUES(2, 'FACEBOOK');
INSERT INTO bl_user_origin(id, origin_name) VALUES(3, 'GOOGLE');
ALTER TABLE bl_user ADD COLUMN nick_name varchar(255) NULL, ADD COLUMN reg_origin_id int8 NOT NULL DEFAULT 1, ADD COLUMN last_login_origin_id int8 NULL, ADD COLUMN pwd_fb varchar(255) NULL, ADD COLUMN last_pwd_change timestamp NULL;
ALTER TABLE bl_user RENAME COLUMN pwd TO pwd_bk;
ALTER TABLE bl_user ADD CONSTRAINT fk_user_reg_origin FOREIGN KEY (reg_origin_id) REFERENCES bl_user_origin(id);
ALTER TABLE bl_user ADD CONSTRAINT fk_user_last_login_origin FOREIGN KEY (last_login_origin_id) REFERENCES bl_user_origin(id);
UPDATE bl_user SET nick_name = 'antsy' where id = 3;
ALTER INDEX UK_rqw4ym2e457u7mvnkervsdf6t RENAME TO uk_user_email;
ALTER INDEX UK_c1hmxwfntwdbqqqk3abcmmit2 RENAME TO uk_user_auth_token;
ALTER TABLE bl_user_role RENAME CONSTRAINT FK4opipv2f26jg6hufwixhjoawo TO fk_userrole__role_id;
ALTER TABLE bl_user_role RENAME CONSTRAINT FKw4i7ypt0dri5hfn4b72doypx TO fk_userrole__user_id;
ALTER INDEX bl_role_pkey RENAME TO pk_role_id;
ALTER INDEX bl_user_pkey RENAME TO pk_user;
ALTER INDEX bl_user_role_pkey RENAME TO pk_user_role;