name: backend-release
#-$(echo `date '+%Y%m%d%H%M%S'`)
on:
  push:
    branches:
      - master
    tags:
      - v1
    paths:
      - 'booklink-backend/*'
#  GITHUB_WORKSPACE
# https://aws.amazon.com/blogs/containers/create-a-ci-cd-pipeline-for-amazon-ecs-with-github-actions-and-aws-codebuild-tests/
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to AWS
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ../../.aws/backend-task-definition.json
          container-name: booklink-backend-contr
          image: 703057871606.dkr.ecr.eu-central-1.amazonaws.com/booklink-backend:latest
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          cluster: booklink-ec2lx-cluster
          wait-for-service-stability: true

# enable ssh session to debug actions runner
# https://github.com/marketplace/actions/debugging-with-tmate
#    steps:
#      - uses: actions/checkout@v1
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v1
