name: Backend-CI

on:
  push:
    branches:
      - master
    tags:
      - v1
    paths:
      - 'booklink-backend/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build and Test
      working-directory: booklink-backend
      run: mvn -B clean verify --file pom.xml
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: booklink-backend/target/booklink-backend.jar
  dockerize:
    runs-on: ubuntu-latest
    needs: build
    name: Build Docker image and deploy
    steps:
      - uses: actions/checkout@v2
      - name: Download Maven build artifact
        uses: actions/download-artifact@v1
        with:
          name: artifact
      - name: Build Docker Image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ls -l
          mkdir -p target
          mv ../artifact/booklink-backend.jar target/
          ls -l target/
          docker build -t "$GITHUB_REPOSITORY:$IMAGE_TAG" .
        working-directory: booklink-backend