name: backend-release
#-$(echo `date '+%Y%m%d%H%M%S'`)
on:
  push:
    branches:
      - master
    tags:
      - v1
    paths:
      - 'booklink-backend/*'
#  GITHUB_WORKSPACE
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to AWS
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: $GITHUB_WORKSPACE/.aws/backend-task-definition.json
          cluster: booklink-ec2lx-cluster
          wait-for-service-stability: true