name: Backend-CI

on:
  push:
    branches:
      - master
    tags:
      - v1
    paths:
      - 'booklink-backend/*'

jobs:
  test-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Maven Build
      working-directory: booklink-backend
      run: mvn -B clean package --file pom.xml
  dockerize:
    runs-on: ubuntu-latest
    needs: test-package
    name: Build Docker image and deploy
    steps:
      - uses: actions/checkout@v2
      - name: Download Maven build artifact
        uses: actions/download-artifact@v1
        with:
          name: artifact
      - name: Build Docker Image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          mkdir -p booklink-backend/target
          mv artifact/booklink-backend*.jar booklink-backend/target
          docker build -t "$GITHUB_REPOSITORY:$IMAGE_TAG" .