name: Backend-release-CI

on:
  push:
    branches:
      - master
    tags:
      - v1
    paths:
      - 'booklink-backend/*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Maven Build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Use JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Maven Package
      working-directory: booklink-backend
      run: mvn -B clean package --file pom.xml
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: booklink-backend/target/booklink-backend.jar
  dockerize:
    runs-on: ubuntu-latest
    name: Dockerize
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Download Maven build artifact
        uses: actions/download-artifact@v1
        with:
          name: artifact
      - name: Build Docker Image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          mkdir -p target
          mv ../artifact/booklink-backend.jar target/
          docker login -u mrazjava -p ${{ secrets.GITHUB_PACKAGES }} docker.pkg.github.com
          docker build -t docker.pkg.github.com/mrazjava/booklink/booklink_backend:latest .
          #docker build -t "$GITHUB_REPOSITORY:$IMAGE_TAG" .
        working-directory: booklink-backend
      - name: Publish Image to Github Packages
        run: |
          docker push docker.pkg.github.com/mrazjava/booklink/booklink_backend:latest