name: web-master

on:
  push:
    branches:
      - master
    tags:
      - v1
    paths:
      - 'booklink-web/**'
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Node build
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Building Frontend
        working-directory: booklink-web
        run: |
          npm install
          yarn lint
          yarn build
      - name: Preparing Docker Image
        working-directory: booklink-web
        run: |
          docker build -t docker.pkg.github.com/mrazjava/booklink/web-master .
          docker tag docker.pkg.github.com/mrazjava/booklink/web-master docker.io/mrazjava/booklink-web-master
      - name: Pushing image to Github Packages
        run: |
          docker login -u mrazjava -p ${{ secrets.GITHUB_PACKAGES }} docker.pkg.github.com
          docker push docker.pkg.github.com/mrazjava/booklink/web-master
      - name: Push image to dockerhub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_LOGIN }} -p ${{ secrets.DOCKERHUB_PASSWORD }} docker.io
          docker push docker.io/mrazjava/booklink-web-master